### ISSUE TITLE
bootstrap.sh failed by camke version

### ISSUE THREAD

**Issue by weishirongzhen** [trustwallet/wallet-core#4344]
brew install cmake on my mac, `cmake --version ` shows `cmake version 4.0.0`

run ./bootstrap.sh comes errors:

```
Downloading gtest...
Downloading libcheck...
Downloading nolhmann_json...
Downloading protobuf...
done.
CMake Error at CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.5 has been removed from CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.

  Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.

```
looks like in `build/local/src/protobuf/protobuf-3.19.2/examples/CMakeLists.txt` set cmake_minimum_required with 2.8.12
```

# Minimum CMake required
cmake_minimum_required(VERSION 2.8.12)
```

**Comment by satoshiotomakan** [comment]
Hi @weishirongzhen, the issue should have been fixed at https://github.com/trustwallet/wallet-core/pull/4343

**Comment by weishirongzhen** [comment]
after pull latest commit， error still happen @satoshiotomakan 

<img width="569" alt="Image" src="https://github.com/user-attachments/assets/a4e8d96d-37bf-4881-ba4c-8fb9c62ab180" />

**Comment by weishirongzhen** [comment]
@satoshiotomakan after I clean all build, even re-clone repo android run bootstrap.sh
still error :
looks there are still some old cmake version when build
<img width="1469" alt="Image" src="https://github.com/user-attachments/assets/04f87441-b711-4006-a79c-eeb581e4b831" />

**Comment by satoshiotomakan** [comment]
Hi @weishirongzhen, could you please try to update to the latest master and retry?

**Comment by Djihanegh** [comment]
I'am facing the same issue 

```CMake Error at CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.5 has been removed from CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.

  Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
```

Any help please ?
